@startuml
class AirPilot {
    + carryGoods(i:VehicleInterface)
    + runningInTheSky(i:VehicleInterface)
    + runningOnWater(i:VehicleInterface)
}
class C919Plane {
    + carryGoods()
    + runningInTheSky()
    + runningOnWater()
}
class Captain {
    + carryGoods(i:VehicleInterface)
    + runningInTheSky(i:VehicleInterface)
    + runningOnWater(i:VehicleInterface)
}
class Titanic {
    + carryGoods()
    + runningInTheSky()
    + runningOnWater()
}
interface VehicleInterface {
    {abstract} + carryGoods()
    {abstract} + runningInTheSky()
    {abstract} + runningOnWater()
}
VehicleInterface <|.. C919Plane
VehicleInterface <|.. Titanic
VehicleInterface <.. AirPilot
VehicleInterface <.. Captain
@enduml