@startuml
abstract class Goods {
    - des : String
    - price : Double
    + getDes()
    + getPrice()
    + setDes()
    + setPrice()
}
class Decaf {
    + Decaf()
}
class Espresso {
    + Espresso()
}
class Coffee {
    - goods : Goods
    + Coffee(goods : Goods)
    + getDes()
    + getPrice()
}
class Milk {
    + Milk(coffee : Coffee)
}
class Caramel {
    + Caramel(coffee : Coffee)
}
Milk -up-|> Coffee
Caramel -up-|> Coffee
Coffee --|> Goods
Coffee *-- Goods
Decaf -up-|> Goods
Espresso -up-|> Goods
@enduml