@startuml
class Base {
}
class ClassA {
    + func1(a:int,b:int)
}
class ClassB {
    + func1(a:int,b:int)
    + func2(a:int,b:int)
    + func3(a:int,b:int)
}
Base <|-- ClassA
Base <|-- ClassB
ClassB *-- ClassA
@enduml